WIKI_ARTICLES["abonnement-flow"] = {
  title: "Abonnement & betaalflow", category: "Processen", tags: ["process"], updated: "Juni 2026", author: "Mehmet Ayhan",
  content: `<p>Dit artikel beschrijft de complete flow van abonnement → betaling → fulfilment, conform de <strong>B2C ketenflow v0.4.1</strong>. De flow hangt af van de wijzigingsdeadline op <strong>T-6</strong>.</p><div class="info-block info-warning"><div class="info-block-icon">⚠️</div><div>De T-6 deadline is cruciaal. Tot zes dagen voor levering kunnen klanten wijzigingen doorvoeren. Op T-6 lockt JUO de bestelling én start de incasso. De Shopify-order ontstaat pas wanneer de betaling definitief is (rond T-4) en verschijnt dan direct als 'paid'.</div></div>`,
  diagram: { title: "Abonnement → Betaling → Levering", nodes: [
    { id: "t6", label: "T-6\nLock + incasso", type: "start", info: { title: "T-6: Lock en incasso start", step: "Stap 1", body: "<p>Op T-6 sluit de wijzigingsperiode voor de klant.</p><h4>Wat gebeurt er:</h4><ul><li>JUO lockt de bestelling — wijzigingen zijn niet meer mogelijk</li><li>De laatste geldige klantkeuze is leidend</li><li>JUO geeft Mollie de incasso-opdracht; Mollie schiet de incasso in bij de banken</li></ul><h4>Let op</h4><p>In Shopify is op dit moment nog géén order zichtbaar.</p>" }},
    { id: "t5-bank", label: "T-5\nBankverwerking", type: "normal", info: { title: "T-5: Verwerking door de bank", step: "Stap 2", body: "<p>De bank van de klant verwerkt de afschrijving.</p><p>Status: de betaling staat bij Mollie op <code>pending</code>.</p>" }},
    { id: "t4-paid", label: "T-4\nPaid + order", type: "decision", info: { title: "T-4: Settlement en ordercreatie", step: "Stap 3", body: "<p>Mollie ontvangt de bevestiging van de bank; de betaling springt op <code>paid</code>.</p><h4>Ordercreatie</h4><ul><li>JUO ontvangt het signaal 'Betaald' en maakt de order aan in Shopify</li><li>De order verschijnt nu pas, direct als <code>paid</code></li><li>Via de middleware gaat de definitieve order naar Odoo</li></ul>" }},
    { id: "odoo-planning", label: "Odoo\nPlanning", type: "normal", info: { title: "Odoo operationele planning", step: "Stap 4", body: "<p>Odoo gebruikt de definitieve order voor alle operationele planning.</p><ul><li>🥕 Productieplanning en stuklijsten</li><li>📦 Inkoop- en voorraadplanning</li><li>🚛 Picking & fulfilment</li><li>🗺️ Transportplanning via NextUp</li></ul>" }},
    { id: "levering", label: "Levering\n🚚", type: "end", info: { title: "Leverdag", step: "Stap 5", body: "<p>Op de leverdag zijn alle systemen gesynchroniseerd.</p><ul><li>Warehouse: picking & packing afgerond</li><li>Transport: routes via NextUp</li><li>Klant ontvangt levering</li></ul>" }},
  ]},
  extraContent: `<h2>Systeemverantwoordelijkheden</h2><ul><li><strong>Juo</strong> — Abonnementen, subscription logic, payment initiation</li><li><strong>Mollie</strong> — PSP, SEPA-incasso</li><li><strong>Shopify</strong> — Orderregistratie, facturatie</li><li><strong>Odoo</strong> — Fulfilment, productie, logistiek</li></ul><h2>Bron</h2><a class="link-block" href="https://mehmetayhan-droid.github.io/processenb2c/" target="_blank"><span class="link-block-icon">🔄</span><div class="link-block-text"><div class="link-block-title">B2C ketenflow v0.4.1 — volledige diagrammen per stap</div><div class="link-block-url">mehmetayhan-droid.github.io/processenb2c</div></div><span class="link-block-arrow">↗</span></a>`
};
